### ISSUE TITLE
Unreachable code in `make.vim`

### ISSUE THREAD

**Issue by Milly** [Shougo/unite-build#9]
[in make.vim L115](https://github.com/Shougo/unite-build/blob/fad711808494404e8ffbd16f03463414d897398c/autoload/unite/sources/build/builders/make.vim#L115)
```vim
  if !filereadable(filename) && '\<\f\+:'
    " Message.
    return { 'type' : 'message', 'text' : string }
  endif
```

Single string in expression, and `return` is unreachable.

**Comment by Shougo** [comment]
Fixed.
